### ISSUE TITLE
curious about reason to use tf.eye

### ISSUE THREAD

**Issue by ssoonan** [alleveenstra/attentionocr#13]
Hi, I ran in to u r code and it gives me a lot help. Thank you.
By the way, I just wonder why u use tf.eye for attention layer.
For many cases, attention layer is implemented by each attention cell and for loop.
tf.eye is okay for implement attention layer at once, but im still curious about why u use it.

**Comment by alleveenstra** [comment]
Great to hear my code helped you! I like the tf.eye construction over a for loop for aesthetic reason, it is in my opinion easier to read this code.
